FROM node:alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ../package.json /app/package.json
RUN npm install -g npm@11.0.0
RUN npm i --verbose
COPY . /app
EXPOSE 80
CMD ["npm", "run", "dev"]